plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
relative_links:
  enabled: true
  collections: true
include:
  - 2023_05_10_20_26_57_dragon_aegis.md
  - README.md
remote_theme: pages-themes/cayman@v0.2.0
title: [Dragon Aegis AD Logs]
# description: [Dragon Aegis AD Logs]